// <auto-generated />
namespace CmsShopingCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BrandTBL_CategoryBrandTbl1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrandTBL_CategoryBrandTbl1));
        
        string IMigrationMetadata.Id
        {
            get { return "201911162231416_BrandTBL_CategoryBrandTbl1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
