// <auto-generated />
namespace CmsShopingCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SetImgSliderImageNameOptinal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetImgSliderImageNameOptinal));
        
        string IMigrationMetadata.Id
        {
            get { return "202010132309384_SetImgSliderImageNameOptinal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
